/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/room.gltf -k -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Clock_Hour_Hand: THREE.Mesh
    Clock_Minute_Hand: THREE.Mesh
    Clock_Second_Hand: THREE.Mesh
    Laptop_Cable_1: THREE.Mesh
    Laptop_Cable_2: THREE.Mesh
    Bed: THREE.Mesh
    Rug: THREE.Mesh
    Rubber_Duck: THREE.Mesh
    Bulbasaur: THREE.Mesh
    Desk: THREE.Mesh
    Shelf_1: THREE.Mesh
    Shelf_2: THREE.Mesh
    Coaster: THREE.Mesh
    Coffee_Mug: THREE.Mesh
    Books: THREE.Mesh
    Floor: THREE.Mesh
    Poster_1: THREE.Mesh
    Poster_2: THREE.Mesh
    Clock_Face: THREE.Mesh
    Baseboard: THREE.Mesh
    Bedside_Lamp: THREE.Mesh
    Bookend: THREE.Mesh
    Desk_Legs: THREE.Mesh
    Desk_Mat: THREE.Mesh
    Laptop: THREE.Mesh
    Monitor: THREE.Mesh
    Mouse: THREE.Mesh
    Nightstand: THREE.Mesh
    Office_Chair: THREE.Mesh
    Pencil_Holder: THREE.Mesh
    Pencils: THREE.Mesh
    Shade: THREE.Mesh
    Standing_Lamp: THREE.Mesh
    Walls: THREE.Mesh
    White_Potted_Plant: THREE.Mesh
    Window: THREE.Mesh
    Corner_Potted_Plant: THREE.Mesh
    Nightstand_Plant: THREE.Mesh
    Keyboard: THREE.Mesh
    Pillow: THREE.Mesh
    Poster_Frame_1: THREE.Mesh
    Poster_Frame_2: THREE.Mesh
    Clock: THREE.Mesh
    Mattress: THREE.Mesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/room.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Clock_Hour_Hand" geometry={nodes.Clock_Hour_Hand.geometry} material={nodes.Clock_Hour_Hand.material} position={[-1.79, 2.91, 0.39]} rotation={[0, 0, -Math.PI / 2]} scale={[1.13, 1, 1.13]} />
      <mesh name="Clock_Minute_Hand" geometry={nodes.Clock_Minute_Hand.geometry} material={nodes.Clock_Minute_Hand.material} position={[-1.79, 2.91, 0.39]} rotation={[0, 0, -Math.PI / 2]} scale={[1.13, 1, 1.13]} />
      <mesh name="Clock_Second_Hand" geometry={nodes.Clock_Second_Hand.geometry} material={nodes.Clock_Second_Hand.material} position={[-1.79, 2.91, 0.39]} rotation={[0, 0, -Math.PI / 2]} scale={[1.13, 1, 1.13]} />
      <mesh name="Laptop_Cable_1" geometry={nodes.Laptop_Cable_1.geometry} material={nodes.Laptop_Cable_1.material} position={[-1.38, 1.11, 0.58]} scale={0.08} />
      <mesh name="Laptop_Cable_2" geometry={nodes.Laptop_Cable_2.geometry} material={nodes.Laptop_Cable_2.material} position={[-1.36, 1.11, 0.57]} scale={0.08} />
      <mesh name="Bed" geometry={nodes.Bed.geometry} material={nodes.Bed.material} position={[1.27, 0.81, 0.82]} scale={[1.09, 1, 1.07]} />
      <mesh name="Rug" geometry={nodes.Rug.geometry} material={nodes.Rug.material} position={[0.56, 0.04, 0.67]} rotation={[0, Math.PI / 2, 0]} scale={[1.21, 1, 1.21]} />
      <mesh name="Rubber_Duck" geometry={nodes.Rubber_Duck.geometry} material={nodes.Rubber_Duck.material} position={[-1.44, 1.1, -0.42]} rotation={[-Math.PI / 2, 0, -0.59]} />
      <mesh name="Bulbasaur" geometry={nodes.Bulbasaur.geometry} material={nodes.Bulbasaur.material} position={[-1.7, 2.69, 1.14]} rotation={[0, 1.57, 0]} />
      <mesh name="Desk" geometry={nodes.Desk.geometry} material={nodes.Desk.material} position={[-1.28, 0.62, 0.07]} />
      <mesh name="Shelf_1" geometry={nodes.Shelf_1.geometry} material={nodes.Shelf_1.material} position={[-1.68, 2.64, 1.31]} />
      <mesh name="Shelf_2" geometry={nodes.Shelf_2.geometry} material={nodes.Shelf_2.material} position={[-1.68, 2, 1.31]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="Coaster" geometry={nodes.Coaster.geometry} material={nodes.Coaster.material} position={[-1.09, 1.1, -0.66]} />
      <mesh name="Coffee_Mug" geometry={nodes.Coffee_Mug.geometry} material={nodes.Coffee_Mug.material} position={[-1.09, 1.19, -0.66]} rotation={[0, -0.52, 0]} scale={[1.04, 1, 1.04]} />
      <mesh name="Books" geometry={nodes.Books.geometry} material={nodes.Books.material} position={[-1.7, 2.24, 1.68]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh name="Floor" geometry={nodes.Floor.geometry} material={nodes.Floor.material} position={[0, 2, 0]} />
      <mesh name="Poster_1" geometry={nodes.Poster_1.geometry} material={nodes.Poster_1.material} position={[1.34, 2.65, -1.81]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="Poster_2" geometry={nodes.Poster_2.geometry} material={nodes.Poster_2.material} position={[-1.82, 2.6, -0.58]} scale={[0.63, 0.86, 0.86]} />
      <mesh name="Clock_Face" geometry={nodes.Clock_Face.geometry} material={nodes.Clock_Face.material} position={[-1.85, 2.91, 0.39]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="Baseboard" geometry={nodes.Baseboard.geometry} material={nodes.Baseboard.material} position={[0, 1.97, 0]} />
      <mesh name="Bedside_Lamp" geometry={nodes.Bedside_Lamp.geometry} material={nodes.Bedside_Lamp.material} position={[0.34, 0.86, -1.52]} scale={1.25} />
      <mesh name="Bookend" geometry={nodes.Bookend.geometry} material={nodes.Bookend.material} position={[-1.69, 2.05, 1.76]} />
      <mesh name="Desk_Legs" geometry={nodes.Desk_Legs.geometry} material={nodes.Desk_Legs.material} position={[-1.28, 0.62, 0.07]} />
      <mesh name="Desk_Mat" geometry={nodes.Desk_Mat.geometry} material={nodes.Desk_Mat.material} position={[-1.05, 1.1, 0.07]} />
      <mesh name="Laptop" geometry={nodes.Laptop.geometry} material={nodes.Laptop.material} position={[-1.11, 1.1, 0.73]} rotation={[0, 0.5, 0]} />
      <mesh name="Monitor" geometry={nodes.Monitor.geometry} material={nodes.Monitor.material} position={[-1.51, 1.56, 0.04]} />
      <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={nodes.Mouse.material} position={[-1.07, 1.12, -0.36]} rotation={[Math.PI / 2, 0, 0.24]} />
      <mesh name="Nightstand" geometry={nodes.Nightstand.geometry} material={nodes.Nightstand.material} position={[0.14, 0.15, -1.32]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Office_Chair" geometry={nodes.Office_Chair.geometry} material={nodes.Office_Chair.material} position={[-0.41, 0.48, 0.16]} rotation={[0, -1.06, 0]} />
      <mesh name="Pencil_Holder" geometry={nodes.Pencil_Holder.geometry} material={nodes.Pencil_Holder.material} position={[-1.5, 1.17, -0.71]} />
      <mesh name="Pencils" geometry={nodes.Pencils.geometry} material={nodes.Pencils.material} position={[-1.5, 1.24, -0.75]} rotation={[-1.03, -1.15, -0.4]} />
      <mesh name="Shade" geometry={nodes.Shade.geometry} material={nodes.Shade.material} position={[-0.32, 3.07, -1.88]} scale={[0.88, 0.88, 1]} />
      <mesh name="Standing_Lamp" geometry={nodes.Standing_Lamp.geometry} material={nodes.Standing_Lamp.material} position={[-1.44, 0.15, -1.43]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Walls" geometry={nodes.Walls.geometry} material={nodes.Walls.material} position={[0, 2, 0]} />
      <mesh name="White_Potted_Plant" geometry={nodes.White_Potted_Plant.geometry} material={nodes.White_Potted_Plant.material} position={[-1.68, 2.85, 1.48]} />
      <mesh name="Window" geometry={nodes.Window.geometry} material={nodes.Window.material} position={[-0.32, 2.35, -2.11]} scale={[0.88, 0.88, 1]} />
      <mesh name="Corner_Potted_Plant" geometry={nodes.Corner_Potted_Plant.geometry} material={nodes.Corner_Potted_Plant.material} position={[-1.27, 0.15, 1.62]} rotation={[0, -0.37, 0]} />
      <mesh name="Nightstand_Plant" geometry={nodes.Nightstand_Plant.geometry} material={nodes.Nightstand_Plant.material} position={[-0.05, 0.86, -1.51]} rotation={[0, 0.96, 0]} />
      <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={nodes.Keyboard.material} position={[-1.03, 1.12, 0.13]} rotation={[-Math.PI, 1.5, -Math.PI]} scale={0.03} />
      <mesh name="Pillow" geometry={nodes.Pillow.geometry} material={nodes.Pillow.material} position={[1.27, 0.81, 0.82]} scale={[1.09, 1, 1.07]} />
      <mesh name="Poster_Frame_1" geometry={nodes.Poster_Frame_1.geometry} material={nodes.Poster_Frame_1.material} position={[1.34, 2.65, -1.81]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="Poster_Frame_2" geometry={nodes.Poster_Frame_2.geometry} material={nodes.Poster_Frame_2.material} position={[-1.82, 2.6, -0.58]} scale={[0.63, 0.86, 0.86]} />
      <mesh name="Clock" geometry={nodes.Clock.geometry} material={nodes.Clock.material} position={[-1.85, 2.91, 0.39]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="Mattress" geometry={nodes.Mattress.geometry} material={nodes.Mattress.material} position={[1.27, 0.81, 0.82]} scale={[1.09, 1, 1.07]} />
    </group>
  )
}

useGLTF.preload('/room.gltf')
