/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/test-room.glb
*/

import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('models/test-room.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Walls.geometry} material={materials.Material} position={[0, 2, 0]} />
      <mesh geometry={nodes.Floor.geometry} material={materials['Material.004']} position={[0.07, 0.15, 0.07]} />
      <mesh geometry={nodes.Desk.geometry} material={materials['Material.005']} position={[-0.82, 1.18, -0.13]} />
      <mesh geometry={nodes.Shelf.geometry} material={materials['Material.003']} position={[-0.83, 2.47, -0.21]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.05, -1]} />
      <mesh geometry={nodes.Mattress.geometry} material={materials['Material.002']} position={[1.23, 0.82, -0.46]} />
      <mesh geometry={nodes.Bed_Frame.geometry} material={materials['Material.001']} position={[1.86, 0.71, 0.56]} scale={0.08} />
    </group>
  )
}

useGLTF.preload('models/test-room.glb');
