/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/room.gltf -k -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Desk_Mat: THREE.Mesh
    ['Node-Mesh']: THREE.Mesh
    ['Node-Mesh_1']: THREE.Mesh
    ['Node-Mesh_2']: THREE.Mesh
    ['LapTop_Cube002-Mesh']: THREE.Mesh
    ['LapTop_Cube002-Mesh_1']: THREE.Mesh
    ['LapTop_Cube002-Mesh_2']: THREE.Mesh
    NightStand_3: THREE.Mesh
    NightStand_3_1: THREE.Mesh
    Lamp_with_shade: THREE.Mesh
    Lamp_with_shade_1: THREE.Mesh
    Lamp_with_shade_2: THREE.Mesh
    Light_Stand1: THREE.Mesh
    Light_Stand1_1: THREE.Mesh
    Bookend: THREE.Mesh
    Baseboard: THREE.Mesh
    mesh1885116500003: THREE.Mesh
    mesh1885116500003_1: THREE.Mesh
    mesh1885116500003_2: THREE.Mesh
    Cube024: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cylinder007_1: THREE.Mesh
    Cube018: THREE.Mesh
    Cube018_1: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cylinder006_1: THREE.Mesh
    Cylinder006_2: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cube016: THREE.Mesh
    Cube016_1: THREE.Mesh
    Hour_Hand: THREE.Mesh
    Minute_Hand: THREE.Mesh
    Cube010: THREE.Mesh
    Cube010_1: THREE.Mesh
    Cube010_2: THREE.Mesh
    Cube013: THREE.Mesh
    Cube013_1: THREE.Mesh
    Cube013_2: THREE.Mesh
    Shelf_Bottom: THREE.Mesh
    Shelf_Top: THREE.Mesh
    Circle002: THREE.Mesh
    Circle002_1: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube007_2: THREE.Mesh
    Cube007_3: THREE.Mesh
    Cube007_4: THREE.Mesh
    Cube007_5: THREE.Mesh
    Cube007_6: THREE.Mesh
    Cube007_7: THREE.Mesh
    Cube007_8: THREE.Mesh
    Rubber_Duck: THREE.Mesh
    model001: THREE.Mesh
    model001_1: THREE.Mesh
    model001_2: THREE.Mesh
    model001_3: THREE.Mesh
    Keyboard_Body_Keyboard_Body1_0002: THREE.Mesh
    Keyboard_Body_Keyboard_Body1_0002_1: THREE.Mesh
    Coaster: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cube015: THREE.Mesh
    Cube015_1: THREE.Mesh
    Cube015_2: THREE.Mesh
    Cube019: THREE.Mesh
    Cube019_1: THREE.Mesh
    Rug: THREE.Mesh
    FiddleleafFigPottedPlant_mesh_1001: THREE.Mesh
    FiddleleafFigPottedPlant_mesh_1001_1: THREE.Mesh
    FiddleleafFigPottedPlant_mesh_1001_2: THREE.Mesh
    Cube004: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube004_2: THREE.Mesh
    Cube004_3: THREE.Mesh
    Cube004_4: THREE.Mesh
    Houseplant_mesh_1002: THREE.Mesh
    Houseplant_mesh_1002_1: THREE.Mesh
    Houseplant_mesh_1002_2: THREE.Mesh
  }
  materials: {
    ['Material.012']: THREE.MeshStandardMaterial
    Executive: THREE.MeshStandardMaterial
    Executive__1: THREE.MeshStandardMaterial
    Executive__2: THREE.MeshStandardMaterial
    ['Laptop Keys']: THREE.MeshStandardMaterial
    lighterGray: THREE.MeshStandardMaterial
    Coffee: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Clock Hand']: THREE.MeshStandardMaterial
    LightMetal: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    Baseboard: THREE.MeshStandardMaterial
    ['mat21.001']: THREE.MeshStandardMaterial
    ['mat20.001']: THREE.MeshStandardMaterial
    ['mat9.001']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Pencil Holder']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Window Light']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Shade: THREE.MeshStandardMaterial
    ['Shelf.001']: THREE.MeshStandardMaterial
    ['Shelf.002']: THREE.MeshStandardMaterial
    ['Clock.001']: THREE.MeshStandardMaterial
    ['Clock Face.001']: THREE.MeshStandardMaterial
    ['Poster Frame.001']: THREE.MeshStandardMaterial
    ['Poster DS']: THREE.MeshStandardMaterial
    ['Poster Watercolor']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['lambert2SG.001']: THREE.MeshStandardMaterial
    ['001BodyB1.001']: THREE.MeshStandardMaterial
    ['001BodyA1.001']: THREE.MeshStandardMaterial
    ['001Iris1.001']: THREE.MeshStandardMaterial
    ['001Eye1.001']: THREE.MeshStandardMaterial
    ['Keyboard_Body1.002']: THREE.MeshStandardMaterial
    ['Keyboard_Keys.002']: THREE.MeshStandardMaterial
    ['Coaster.001']: THREE.MeshStandardMaterial
    ['Coffee Mug.001']: THREE.MeshStandardMaterial
    ['Coffee.001']: THREE.MeshStandardMaterial
    ['Wall 2.001']: THREE.MeshStandardMaterial
    ['Floor.001']: THREE.MeshStandardMaterial
    ['Wall 1.001']: THREE.MeshStandardMaterial
    ['Desk Top.001']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Rug.001']: THREE.MeshStandardMaterial
    ['FiddleleafFigPottedPlant_mat.001']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Mattress.001']: THREE.MeshStandardMaterial
    ['Bed Frame.001']: THREE.MeshStandardMaterial
    ['Blanket Inner.001']: THREE.MeshStandardMaterial
    ['Blanket Outer.001']: THREE.MeshStandardMaterial
    ['Pillow.001']: THREE.MeshStandardMaterial
    ['Houseplant_mat1.001']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
  }
}

export function Room(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/room.gltf') as GLTFResult
  const texture = useTexture('/textures/baked.jpg');
  texture.flipY = false;
  const textureMaterial = new THREE.MeshStandardMaterial({ map: texture });
  
  return (
    <group {...props} dispose={null}>
      <mesh name="Desk_Mat" geometry={nodes.Desk_Mat.geometry} material={textureMaterial} position={[-1.05, 1.1, 0.07]} />
      <group name="Office_Chair" position={[-0.41, 0.48, 0.16]} rotation={[0, -1.06, 0]}>
        <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={textureMaterial} />
      </group>
      <group name="Laptop" position={[-1.11, 1.1, 0.73]} rotation={[0, 0.5, 0]}>
        <mesh name="LapTop_Cube002-Mesh" geometry={nodes['LapTop_Cube002-Mesh'].geometry} material={textureMaterial} />
        <mesh name="LapTop_Cube002-Mesh_1" geometry={nodes['LapTop_Cube002-Mesh_1'].geometry} material={textureMaterial} />
        <mesh name="LapTop_Cube002-Mesh_2" geometry={nodes['LapTop_Cube002-Mesh_2'].geometry} material={textureMaterial} />
      </group>
      <group name="Nightstand" position={[0.14, 0.15, -1.32]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="NightStand_3" geometry={nodes.NightStand_3.geometry} material={textureMaterial} />
        <mesh name="NightStand_3_1" geometry={nodes.NightStand_3_1.geometry} material={textureMaterial} />
      </group>
      <group name="Bedside_Lamp" position={[0.34, 0.86, -1.52]}>
        <mesh name="Lamp_with_shade" geometry={nodes.Lamp_with_shade.geometry} material={textureMaterial} />
        <mesh name="Lamp_with_shade_1" geometry={nodes.Lamp_with_shade_1.geometry} material={textureMaterial} />
        <mesh name="Lamp_with_shade_2" geometry={nodes.Lamp_with_shade_2.geometry} material={textureMaterial} />
      </group>
      <group name="Standing_Lamp" position={[-1.44, 0.15, -1.43]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Light_Stand1" geometry={nodes.Light_Stand1.geometry} material={textureMaterial} />
        <mesh name="Light_Stand1_1" geometry={nodes.Light_Stand1_1.geometry} material={textureMaterial} />
      </group>
      <mesh name="Bookend" geometry={nodes.Bookend.geometry} material={textureMaterial} position={[-1.69, 2.05, 1.76]} />
      <mesh name="Baseboard" geometry={nodes.Baseboard.geometry} material={textureMaterial} position={[0, 1.97, 0]} />
      <group name="White_Potted_Plant" position={[-1.68, 2.85, 1.48]}>
        <mesh name="mesh1885116500003" geometry={nodes.mesh1885116500003.geometry} material={textureMaterial} />
        <mesh name="mesh1885116500003_1" geometry={nodes.mesh1885116500003_1.geometry} material={textureMaterial} />
        <mesh name="mesh1885116500003_2" geometry={nodes.mesh1885116500003_2.geometry} material={textureMaterial} />
      </group>
      <group name="Mouse" position={[-1, 1.12, -0.35]} rotation={[0, -0.24, 0]}>
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={textureMaterial} />
        <mesh name="Cube024_1" geometry={nodes.Cube024_1.geometry} material={textureMaterial} />
      </group>
      <group name="Blue_Pen" position={[-1.54, 1.24, -0.69]} rotation={[-2.4, 0.9, 2.01]}>
        <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={textureMaterial} />
        <mesh name="Cylinder007_1" geometry={nodes.Cylinder007_1.geometry} material={textureMaterial} />
      </group>
      <group name="Pencil_Holder" position={[-1.5, 1.17, -0.71]}>
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={textureMaterial} />
        <mesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={textureMaterial} />
      </group>
      <group name="Pencils" position={[-1.46, 1.23, -0.75]} rotation={[0.14, 0.84, -0.32]}>
        <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={textureMaterial} />
        <mesh name="Cylinder006_1" geometry={nodes.Cylinder006_1.geometry} material={textureMaterial} />
        <mesh name="Cylinder006_2" geometry={nodes.Cylinder006_2.geometry} material={textureMaterial} />
      </group>
      <group name="Red_Pen" position={[-1.5, 1.24, -0.75]} rotation={[-1.03, -1.15, -0.4]}>
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={textureMaterial} />
        <mesh name="Cylinder005_1" geometry={nodes.Cylinder005_1.geometry} material={textureMaterial} />
      </group>
      <group name="Monitor" position={[-1.51, 1.56, 0.04]}>
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={textureMaterial} />
        <mesh name="Cube016_1" geometry={nodes.Cube016_1.geometry} material={textureMaterial} />
      </group>
      <mesh name="Hour_Hand" geometry={nodes.Hour_Hand.geometry} material={textureMaterial} position={[-1.79, 2.91, 0.48]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="Minute_Hand" geometry={nodes.Minute_Hand.geometry} material={textureMaterial} position={[-1.79, 2.91, 0.48]} rotation={[0, 0, -Math.PI / 2]} />
      <group name="Window_Frame" position={[-0.32, 2.35, -2.11]}>
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={textureMaterial} />
        <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={textureMaterial} />
        <mesh name="Cube010_2" geometry={nodes.Cube010_2.geometry} material={textureMaterial} />
      </group>
      <group name="Window_Shade" position={[-0.33, 3.05, -1.87]}>
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={textureMaterial} />
        <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={textureMaterial} />
        <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={textureMaterial} />
      </group>
      <mesh name="Shelf_Bottom" geometry={nodes.Shelf_Bottom.geometry} material={textureMaterial} position={[-1.68, 2, 1.31]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="Shelf_Top" geometry={nodes.Shelf_Top.geometry} material={textureMaterial} position={[-1.68, 2.64, 1.31]} />
      <group name="Clock" position={[-1.85, 2.91, 0.48]} rotation={[0, 0, -Math.PI / 2]} scale={[1.13, 1, 1.13]}>
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={textureMaterial} />
        <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={textureMaterial} />
      </group>
      <group name="Poster_DS" position={[1.34, 2.65, -1.81]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={textureMaterial} />
        <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={textureMaterial} />
      </group>
      <group name="Poster_Watercolor" position={[-1.82, 2.68, -0.63]} scale={[0.63, 1, 1]}>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={textureMaterial} />
        <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={textureMaterial} />
      </group>
      <group name="Books" position={[-1.7, 2.24, 1.68]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={textureMaterial} />
        <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={textureMaterial} />
        <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={textureMaterial} />
        <mesh name="Cube007_3" geometry={nodes.Cube007_3.geometry} material={textureMaterial} />
        <mesh name="Cube007_4" geometry={nodes.Cube007_4.geometry} material={textureMaterial} />
        <mesh name="Cube007_5" geometry={nodes.Cube007_5.geometry} material={textureMaterial} />
        <mesh name="Cube007_6" geometry={nodes.Cube007_6.geometry} material={textureMaterial} />
        <mesh name="Cube007_7" geometry={nodes.Cube007_7.geometry} material={textureMaterial} />
        <mesh name="Cube007_8" geometry={nodes.Cube007_8.geometry} material={textureMaterial} />
      </group>
      <mesh name="Rubber_Duck" geometry={nodes.Rubber_Duck.geometry} material={textureMaterial} position={[-1.44, 1.1, -0.42]} rotation={[-Math.PI / 2, 0, -0.59]} />
      <group name="Bulbasaur" position={[-1.7, 2.69, 1.14]} rotation={[0, 1.57, 0]}>
        <mesh name="model001" geometry={nodes.model001.geometry} material={textureMaterial} />
        <mesh name="model001_1" geometry={nodes.model001_1.geometry} material={textureMaterial} />
        <mesh name="model001_2" geometry={nodes.model001_2.geometry} material={textureMaterial} />
        <mesh name="model001_3" geometry={nodes.model001_3.geometry} material={textureMaterial} />
      </group>
      <group name="Keyboard" position={[-1.03, 1.11, 0.1]} rotation={[-Math.PI, 1.51, -Math.PI]} scale={0.03}>
        <mesh name="Keyboard_Body_Keyboard_Body1_0002" geometry={nodes.Keyboard_Body_Keyboard_Body1_0002.geometry} material={textureMaterial} />
        <mesh name="Keyboard_Body_Keyboard_Body1_0002_1" geometry={nodes.Keyboard_Body_Keyboard_Body1_0002_1.geometry} material={textureMaterial} />
      </group>
      <mesh name="Coaster" geometry={nodes.Coaster.geometry} material={textureMaterial} position={[-1.09, 1.1, -0.66]} scale={[1.13, 1, 1.13]} />
      <group name="Coffee_Mug" position={[-1.09, 1.19, -0.66]} rotation={[0, -1.09, 0]}>
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={textureMaterial} />
        <mesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={textureMaterial} />
      </group>
      <group name="Walls" position={[0, 2, 0]}>
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={textureMaterial} />
        <mesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={textureMaterial} />
        <mesh name="Cube015_2" geometry={nodes.Cube015_2.geometry} material={textureMaterial} />
      </group>
      <group name="Desk" position={[-1.28, 0.62, 0.07]}>
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={textureMaterial} />
        <mesh name="Cube019_1" geometry={nodes.Cube019_1.geometry} material={textureMaterial} />
      </group>
      <mesh name="Rug" geometry={nodes.Rug.geometry} material={textureMaterial} position={[0.56, 0.04, 0.67]} rotation={[0, Math.PI / 2, 0]} scale={[1.21, 1, 1.21]} />
      <group name="Corner_Potted_Plant" position={[-1.27, 0.15, 1.62]} rotation={[0, -0.37, 0]}>
        <mesh name="FiddleleafFigPottedPlant_mesh_1001" geometry={nodes.FiddleleafFigPottedPlant_mesh_1001.geometry} material={textureMaterial} />
        <mesh name="FiddleleafFigPottedPlant_mesh_1001_1" geometry={nodes.FiddleleafFigPottedPlant_mesh_1001_1.geometry} material={textureMaterial} />
        <mesh name="FiddleleafFigPottedPlant_mesh_1001_2" geometry={nodes.FiddleleafFigPottedPlant_mesh_1001_2.geometry} material={textureMaterial} />
      </group>
      <group name="Bed" position={[1.27, 0.62, -0.42]}>
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={textureMaterial} />
        <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={textureMaterial} />
        <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={textureMaterial} />
        <mesh name="Cube004_3" geometry={nodes.Cube004_3.geometry} material={textureMaterial} />
        <mesh name="Cube004_4" geometry={nodes.Cube004_4.geometry} material={textureMaterial} />
      </group>
      <group name="Nightstand_Potted_Plant" position={[-0.05, 0.86, -1.51]} rotation={[0, 0.96, 0]}>
        <mesh name="Houseplant_mesh_1002" geometry={nodes.Houseplant_mesh_1002.geometry} material={textureMaterial} />
        <mesh name="Houseplant_mesh_1002_1" geometry={nodes.Houseplant_mesh_1002_1.geometry} material={textureMaterial} />
        <mesh name="Houseplant_mesh_1002_2" geometry={nodes.Houseplant_mesh_1002_2.geometry} material={textureMaterial} />
      </group>
    </group>
  )
}

useGLTF.preload('models/room.gltf')
